# Tensorflow Basics

TensorFlow is an open source software library for numerical computation using data flow graphs. In other words, the best way to build deep learning models.

In this tutorial, we will learn about the basics of TensorFlow. We will begin by understanding the data structure of tensor.

In [8]:
import numpy as np
import tensorflow as tf
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
import matplotlib.pyplot as plt

In [9]:
import numpy as np
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
print (tensor_1d)

[ 1.3   1.    4.   23.99]


We have initialized two matrix constants m1 and m2. dot_operation stores the result of matmul (matrix multiplication) of m1 and m2. tf.constant() creates a constant Tensor. tf.matmul() returns a Tensor of same type as m1 and m2.

In [10]:
m1 = tf.constant([[2,2]])
m2 = tf.constant([[3],[3]])
dot_operation = tf.matmul(m1,m2)

    

The result won't get printed directly.

In [11]:
print(dot_operation)

Tensor("MatMul:0", shape=(1, 1), dtype=int32)


We need to create session and run the operation.

# What is a session in TensorFlow?
A Session object encapsulates the environment in which Operation objects are executed, and Tensor objects are evaluated.

In [13]:


sess = tf.compat.v1.Session()
print(sess.run(dot_operation))


[[12]]


In [26]:
with tf.Session() as sess:
    a="hi"
    print(a)

hi


In [14]:

hello = tf.constant('Hello, Welcome')

sess = tf.compat.v1.Session()

print(sess.run(hello))

b'Hello, Welcome'


# Tensor Handling and Manipulations


In [34]:
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')

print ("matrix1\n",matrix1)
print ("matrix2\n",matrix2)

matrix1
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
matrix2
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [35]:
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)

In [37]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')
print (matrix_3)
matrix_det = tf.matrix_determinant(matrix_3)

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


In [40]:
with tf.Session() as sess:
   result1 = sess.run(matrix_product)
   result2 = sess.run(matrix_sum)
   result3 = sess.run(matrix_det)

print ("matrix_product\n",result1)
print ("matrix_sum\n",result2)
print ("matrix_determinet=",result3)

matrix_product
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
matrix_sum
 [[3 3 3]
 [3 3 3]
 [3 3 3]]
matrix_determinet= 55.999992


# Explanation
We have created multidimensional arrays in the above source code. Now, it is important to understand that we created graph and sessions, which manage the Tensors and generate the appropriate output. With the help of graph, we have the output specifying the mathematical calculations between Tensors.

# Variables
A TensorFlow variable is a way to represent shared, persistent state manipulated by your program. A tf.Variable exsts outside the context of a single session.run call. This happens even for the variables defined in the session. sess.run(tf.global_variables_initializer()) initializes all global variables.

In [42]:
var = tf.Variable(8)

In [48]:
add_operation = tf.add(var, 1)          # returns var + 1 of same type as var
update_operation = tf.assign(var, add_operation)      # var will hold new value add_operation

tf.assign() is the method available in the Variable class which is used to assign the new tf.Tensor to the variable. The new value must have the same shape and dtype as the old Variable value.

In [55]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for _ in range(3):
        sess.run(update_operation)
        print(sess.run(var))

9
10
11


# Placeholder
A placeholder is a variable to which we assign data to a later date. It allows us to create out operations and buid our computation graph, without needing the data. In TensorFlow terms, we feed the data into the graph through these placeholders.

In [60]:
x1 = tf.placeholder(dtype=tf.float32, shape=None)
y1 = tf.placeholder(dtype=tf.float32, shape=None)
z1 = x1 + y1

In [61]:
x2 = tf.placeholder(dtype=tf.float32, shape=[2,1])
y2 = tf.placeholder(dtype=tf.float32, shape=[1,2])
z2 = tf.matmul(x2, y2)

In [67]:
with tf.Session() as sess:
    # running one operation
    x1_value = sess.run(x1, feed_dict={x1: 5})
    print(x1_value)
    
    # running two operations at once
    z1_value, z2_value = sess.run(
    [z1, z2],
    feed_dict = {
        x1:1, y1:2,
        x2:[[2],[3]], y2:[[3,3]]
    })
    print(z1_value)
    print(z2_value)

5.0
3.0
[[6. 6.]
 [9. 9.]]


While working with TensorFlow many times we need to generate evenly-spaced values in an interval. tensorflow. linspace(): This method takes starting tensor, ending tensor, number of values and axis and returns a Tensor with specified number of evenly spaced values

In [16]:
n_values = 32
x = tf.linspace(-3.0, 3.0, n_values)

In [17]:
sess = tf.compat.v1.Session()

print(sess.run(x))

[-3.         -2.8064516  -2.612903   -2.419355   -2.2258065  -2.032258
 -1.8387097  -1.6451614  -1.451613   -1.2580645  -1.0645162  -0.87096786
 -0.6774194  -0.48387098 -0.29032278 -0.09677434  0.0967741   0.29032254
  0.48387098  0.6774192   0.8709676   1.0645161   1.2580643   1.451613
  1.6451612   1.8387094   2.032258    2.2258062   2.4193544   2.612903
  2.8064513   3.        ]


In [77]:
x.eval(session=sess)

array([-3.        , -2.8064516 , -2.612903  , -2.419355  , -2.2258065 ,
       -2.032258  , -1.8387097 , -1.6451614 , -1.451613  , -1.2580645 ,
       -1.0645162 , -0.87096786, -0.6774194 , -0.48387098, -0.29032278,
       -0.09677434,  0.0967741 ,  0.29032254,  0.48387098,  0.6774192 ,
        0.8709676 ,  1.0645161 ,  1.2580643 ,  1.451613  ,  1.6451612 ,
        1.8387094 ,  2.032258  ,  2.2258062 ,  2.4193544 ,  2.612903  ,
        2.8064513 ,  3.        ], dtype=float32)

In [21]:
A1=tf.ones([3,2], tf.int32)
print(A1)
sess = tf.compat.v1.Session()

print(sess.run(A1))



Tensor("ones_1:0", shape=(3, 2), dtype=int32)
[[1 1]
 [1 1]
 [1 1]]


In [22]:

    
    #Zeros function
B1=tf.zeros([3,2])
print(B1)
sess = tf.compat.v1.Session()

print(sess.run(B1))



Tensor("zeros_1:0", shape=(3, 2), dtype=float32)
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
A1=tf.constant([1,2,3,4])
A23=tf.constant([[1,2,3], [4,5,6]])

#create ones tensor and perform element wise multiplication
B1=tf.ones_like(A1)
B23=tf.ones_like(A23)


print(sess.run(B1))
print(sess.run(B23))


[1 1 1 1]
[[1 1 1]
 [1 1 1]]


In [30]:
#fill method
c33=tf.fill([3,3], 7)

print(sess.run(c33))

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# Thank you
## Author

<a href="https://www.linkedin.com/in/muhammad-bilal-afzal-95b33323b/">MUHAMMAD BILAL</a>